modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="purechaos"
version="1.0.4"
displayName="Pure Chaos"
displayURL="https://modrinth.com/mod/chaos"
logoFile="logo.png"
credits="We got ideas from various sources such as PhoenixSC, r/PhoenixSC, itsJim, r/Minecraft and other!"
authors="VikkiVuk, JosipTLG, X Master Woo"
description="Add a little bit of, spice."

[[dependencies.purechaos]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.purechaos]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

