modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
modId="purechaos"
version="1.0.4"
displayName="Pure Chaos"
credits="We got ideas from various sources such as PhoenixSC, r/PhoenixSC, itsJim, r/Minecraft and other!"
displayURL="https://modrinth.com/mod/chaos"
logoFile="logo.png"
authors="VikkiVuk, JosipTLG, X Master Woo"
description='''
Add a little bit of, spice.
'''

[[dependencies.purechaos]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




