modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
modId="chaosmod"
version="1.0.3"
displayName="Pure Chaos"
credits="All credits go to our sponsor, you!"
displayURL="https://vikkivuk.xyz"
authors="VikkiVuk, JosipTLG, X Master Woo, GalaxyHunterGT"
description='''
This mod is everything but normal
'''

[[dependencies.chaosmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




