modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="chaosmod"
version="1.0.0"
displayName="chaosmod"
credits="All credits go to our sponsor, you!"
displayURL="https://github.com/VikkiVuk/chaosmod_together"
authors="VikkiVuk, JosipTLG"
description='''
Just a random mod, nothing special...
'''

[[dependencies.chaosmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




