
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package xyz.aflkonstukt.purechaos.init;

import xyz.aflkonstukt.purechaos.item.ZenithItem;
import xyz.aflkonstukt.purechaos.item.XiteItem;
import xyz.aflkonstukt.purechaos.item.XSORDItem;
import xyz.aflkonstukt.purechaos.item.WoodDimensionItem;
import xyz.aflkonstukt.purechaos.item.WaterCupItem;
import xyz.aflkonstukt.purechaos.item.UseInEmergenciesItem;
import xyz.aflkonstukt.purechaos.item.TurtleArmorItem;
import xyz.aflkonstukt.purechaos.item.TotemOfDreamItem;
import xyz.aflkonstukt.purechaos.item.TotemOfAmogusItem;
import xyz.aflkonstukt.purechaos.item.TintedGlassBottleItem;
import xyz.aflkonstukt.purechaos.item.TesticleOnStickItem;
import xyz.aflkonstukt.purechaos.item.TOItem;
import xyz.aflkonstukt.purechaos.item.SussySusStewItem;
import xyz.aflkonstukt.purechaos.item.SusSwordItem;
import xyz.aflkonstukt.purechaos.item.SusItem;
import xyz.aflkonstukt.purechaos.item.StaravodaItem;
import xyz.aflkonstukt.purechaos.item.SpitBallItem;
import xyz.aflkonstukt.purechaos.item.SpearItem;
import xyz.aflkonstukt.purechaos.item.ScratestItem;
import xyz.aflkonstukt.purechaos.item.SasiAmangasItem;
import xyz.aflkonstukt.purechaos.item.SamsungNote7Item;
import xyz.aflkonstukt.purechaos.item.SSSRItem;
import xyz.aflkonstukt.purechaos.item.RockItem;
import xyz.aflkonstukt.purechaos.item.RadiationLiquidItem;
import xyz.aflkonstukt.purechaos.item.PufferBalloonItem;
import xyz.aflkonstukt.purechaos.item.PotatoSpudsItem;
import xyz.aflkonstukt.purechaos.item.PoopItem;
import xyz.aflkonstukt.purechaos.item.PolandItemItem;
import xyz.aflkonstukt.purechaos.item.PickaxItem;
import xyz.aflkonstukt.purechaos.item.PeemensionItem;
import xyz.aflkonstukt.purechaos.item.PeeItem;
import xyz.aflkonstukt.purechaos.item.OrangeFluidItem;
import xyz.aflkonstukt.purechaos.item.OilItem;
import xyz.aflkonstukt.purechaos.item.ObamiumItem;
import xyz.aflkonstukt.purechaos.item.NetheritPickaxItem;
import xyz.aflkonstukt.purechaos.item.Milk2Item;
import xyz.aflkonstukt.purechaos.item.MethItem;
import xyz.aflkonstukt.purechaos.item.MercuryItem;
import xyz.aflkonstukt.purechaos.item.MelatoninPillItem;
import xyz.aflkonstukt.purechaos.item.LavaBottleItem;
import xyz.aflkonstukt.purechaos.item.KondomnepitajzastoovoradimalispoileralertonimarupuItem;
import xyz.aflkonstukt.purechaos.item.KentuckyFriedChickenItem;
import xyz.aflkonstukt.purechaos.item.KentuckyFriedChickenFriesItem;
import xyz.aflkonstukt.purechaos.item.KFCEItem;
import xyz.aflkonstukt.purechaos.item.JosipRangeItem;
import xyz.aflkonstukt.purechaos.item.JavelinLauncherItem;
import xyz.aflkonstukt.purechaos.item.IronEggItem;
import xyz.aflkonstukt.purechaos.item.InfiniteFuelItem;
import xyz.aflkonstukt.purechaos.item.ImpostorKnifeItem;
import xyz.aflkonstukt.purechaos.item.IglaItem;
import xyz.aflkonstukt.purechaos.item.HalfGoldenAppleItem;
import xyz.aflkonstukt.purechaos.item.GrimaceShakeItem;
import xyz.aflkonstukt.purechaos.item.GlowItem;
import xyz.aflkonstukt.purechaos.item.GatoradeItem;
import xyz.aflkonstukt.purechaos.item.FryingPanItem;
import xyz.aflkonstukt.purechaos.item.FortniteA1Item;
import xyz.aflkonstukt.purechaos.item.FooditemItem;
import xyz.aflkonstukt.purechaos.item.FoodItem3Item;
import xyz.aflkonstukt.purechaos.item.FoodItem2Item;
import xyz.aflkonstukt.purechaos.item.FishLauncherItem;
import xyz.aflkonstukt.purechaos.item.FallgaysItem;
import xyz.aflkonstukt.purechaos.item.FASTTOPASSItem;
import xyz.aflkonstukt.purechaos.item.EdibleWaterBucketItem;
import xyz.aflkonstukt.purechaos.item.EatableCommandBlockItem;
import xyz.aflkonstukt.purechaos.item.DoritoNachoItem;
import xyz.aflkonstukt.purechaos.item.DoritoCoolRanchItem;
import xyz.aflkonstukt.purechaos.item.DirtswordItem;
import xyz.aflkonstukt.purechaos.item.DipexItem;
import xyz.aflkonstukt.purechaos.item.DingotItem;
import xyz.aflkonstukt.purechaos.item.DeekItem;
import xyz.aflkonstukt.purechaos.item.CumItem;
import xyz.aflkonstukt.purechaos.item.CorruptstaffItem;
import xyz.aflkonstukt.purechaos.item.CommunismOrbItem;
import xyz.aflkonstukt.purechaos.item.ComicallyLargeSpoonItem;
import xyz.aflkonstukt.purechaos.item.CocaColaItem;
import xyz.aflkonstukt.purechaos.item.CobbleFluidItem;
import xyz.aflkonstukt.purechaos.item.CioaoItem;
import xyz.aflkonstukt.purechaos.item.CarbonMonoxideItem;
import xyz.aflkonstukt.purechaos.item.BulletItem;
import xyz.aflkonstukt.purechaos.item.BrownItem;
import xyz.aflkonstukt.purechaos.item.BrazilItem;
import xyz.aflkonstukt.purechaos.item.BrakeFluidItem;
import xyz.aflkonstukt.purechaos.item.BottleOfPissItem;
import xyz.aflkonstukt.purechaos.item.BleachItem;
import xyz.aflkonstukt.purechaos.item.BeengotItem;
import xyz.aflkonstukt.purechaos.item.BeefItem;
import xyz.aflkonstukt.purechaos.item.BeefArmorItem;
import xyz.aflkonstukt.purechaos.item.BaguetteItem;
import xyz.aflkonstukt.purechaos.item.AppleIngotItem;
import xyz.aflkonstukt.purechaos.item.AmugusItem;
import xyz.aflkonstukt.purechaos.item.AmogusGunItem;
import xyz.aflkonstukt.purechaos.item.AlmondWaterItem;
import xyz.aflkonstukt.purechaos.item.AetherItem;
import xyz.aflkonstukt.purechaos.item.AdidasSwordItem;
import xyz.aflkonstukt.purechaos.item.AdidasShovelItem;
import xyz.aflkonstukt.purechaos.item.AdidasPickaxeItem;
import xyz.aflkonstukt.purechaos.item.AdidasHoeItem;
import xyz.aflkonstukt.purechaos.item.AdidasAxeItem;
import xyz.aflkonstukt.purechaos.item.AdidasArmorItem;
import xyz.aflkonstukt.purechaos.item.AK47Item;
import xyz.aflkonstukt.purechaos.PurechaosMod;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.common.DeferredSpawnEggItem;
import net.neoforged.bus.api.IEventBus;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;
import net.minecraft.core.registries.BuiltInRegistries;

public class PurechaosModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(BuiltInRegistries.ITEM, PurechaosMod.MODID);
	public static final DeferredHolder<Item, Item> DIRTSWORD = REGISTRY.register("dirtsword", () -> new DirtswordItem());
	public static final DeferredHolder<Item, Item> PEE_BUCKET = REGISTRY.register("pee_bucket", () -> new PeeItem());
	public static final DeferredHolder<Item, Item> PEEMENSION = REGISTRY.register("peemension", () -> new PeemensionItem());
	public static final DeferredHolder<Item, Item> PEE_BLOCK = block(PurechaosModBlocks.PEE_BLOCK);
	public static final DeferredHolder<Item, Item> PICKAX = REGISTRY.register("pickax", () -> new PickaxItem());
	public static final DeferredHolder<Item, Item> FOODITEM = REGISTRY.register("fooditem", () -> new FooditemItem());
	public static final DeferredHolder<Item, Item> AENTITY_SPAWN_EGG = REGISTRY.register("aentity_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.AENTITY, -13434625, -10040065, new Item.Properties()));
	public static final DeferredHolder<Item, Item> FOOD_ITEM_2 = REGISTRY.register("food_item_2", () -> new FoodItem2Item());
	public static final DeferredHolder<Item, Item> POTATO_SPUDS = REGISTRY.register("potato_spuds", () -> new PotatoSpudsItem());
	public static final DeferredHolder<Item, Item> POTATUS = block(PurechaosModBlocks.POTATUS);
	public static final DeferredHolder<Item, Item> WOOD_DIMENSION = REGISTRY.register("wood_dimension", () -> new WoodDimensionItem());
	public static final DeferredHolder<Item, Item> FOOD_ITEM_3 = REGISTRY.register("food_item_3", () -> new FoodItem3Item());
	public static final DeferredHolder<Item, Item> DIPEX = REGISTRY.register("dipex", () -> new DipexItem());
	public static final DeferredHolder<Item, Item> TRIDENT_SPAWN_EGG = REGISTRY.register("trident_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.TRIDENT, -13641874, -1, new Item.Properties()));
	public static final DeferredHolder<Item, Item> DEATH = block(PurechaosModBlocks.DEATH);
	public static final DeferredHolder<Item, Item> SA_DS = block(PurechaosModBlocks.SA_DS);
	public static final DeferredHolder<Item, Item> NETHERIT_PICKAX = REGISTRY.register("netherit_pickax", () -> new NetheritPickaxItem());
	public static final DeferredHolder<Item, Item> EMEPEE = block(PurechaosModBlocks.EMEPEE);
	public static final DeferredHolder<Item, Item> COMICALLY_LARGE_SPOON = REGISTRY.register("comically_large_spoon", () -> new ComicallyLargeSpoonItem());
	public static final DeferredHolder<Item, Item> SPEAR = REGISTRY.register("spear", () -> new SpearItem());
	public static final DeferredHolder<Item, Item> SUS_BLOCK = block(PurechaosModBlocks.SUS_BLOCK);
	public static final DeferredHolder<Item, Item> CUM_BUCKET = REGISTRY.register("cum_bucket", () -> new CumItem());
	public static final DeferredHolder<Item, Item> AMONG_US_SPAWN_EGG = REGISTRY.register("among_us_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.AMONG_US, -52429, -3394816, new Item.Properties()));
	public static final DeferredHolder<Item, Item> SUS = REGISTRY.register("sus", () -> new SusItem());
	public static final DeferredHolder<Item, Item> AMOGUS_2_SPAWN_EGG = REGISTRY.register("amogus_2_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.AMOGUS_2, -26215, -52429, new Item.Properties()));
	public static final DeferredHolder<Item, Item> AMOGUS_3_SPAWN_EGG = REGISTRY.register("amogus_3_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.AMOGUS_3, -52429, -39322, new Item.Properties()));
	public static final DeferredHolder<Item, Item> STARAVODA_BUCKET = REGISTRY.register("staravoda_bucket", () -> new StaravodaItem());
	public static final DeferredHolder<Item, Item> TLGHD = block(PurechaosModBlocks.TLGHD);
	public static final DeferredHolder<Item, Item> AMUGUS_HELMET = REGISTRY.register("amugus_helmet", () -> new AmugusItem.Helmet());
	public static final DeferredHolder<Item, Item> AMUGUS_CHESTPLATE = REGISTRY.register("amugus_chestplate", () -> new AmugusItem.Chestplate());
	public static final DeferredHolder<Item, Item> AMUGUS_LEGGINGS = REGISTRY.register("amugus_leggings", () -> new AmugusItem.Leggings());
	public static final DeferredHolder<Item, Item> AMUGUS_BOOTS = REGISTRY.register("amugus_boots", () -> new AmugusItem.Boots());
	public static final DeferredHolder<Item, Item> SUS_SWORD = REGISTRY.register("sus_sword", () -> new SusSwordItem());
	public static final DeferredHolder<Item, Item> ORANGE_FLUID_BUCKET = REGISTRY.register("orange_fluid_bucket", () -> new OrangeFluidItem());
	public static final DeferredHolder<Item, Item> OIL_BUCKET = REGISTRY.register("oil_bucket", () -> new OilItem());
	public static final DeferredHolder<Item, Item> GATORADE_BUCKET = REGISTRY.register("gatorade_bucket", () -> new GatoradeItem());
	public static final DeferredHolder<Item, Item> GREEN_PLANT = block(PurechaosModBlocks.GREEN_PLANT);
	public static final DeferredHolder<Item, Item> SPLANK_SPAWN_EGG = REGISTRY.register("splank_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.SPLANK, -3355648, -154, new Item.Properties()));
	public static final DeferredHolder<Item, Item> IKEA_DESK_SPAWN_EGG = REGISTRY.register("ikea_desk_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.IKEA_DESK, -13421773, -1, new Item.Properties()));
	public static final DeferredHolder<Item, Item> FALLGAYS = REGISTRY.register("fallgays", () -> new FallgaysItem());
	public static final DeferredHolder<Item, Item> SASI_AMANGAS = REGISTRY.register("sasi_amangas", () -> new SasiAmangasItem());
	public static final DeferredHolder<Item, Item> JOSIP_SPAWN_EGG = REGISTRY.register("josip_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.JOSIP, -3407617, -16777216, new Item.Properties()));
	public static final DeferredHolder<Item, Item> BROWN = REGISTRY.register("brown", () -> new BrownItem());
	public static final DeferredHolder<Item, Item> CARBON_MONOXIDE_BUCKET = REGISTRY.register("carbon_monoxide_bucket", () -> new CarbonMonoxideItem());
	public static final DeferredHolder<Item, Item> CORRUPTSTAFF = REGISTRY.register("corruptstaff", () -> new CorruptstaffItem());
	public static final DeferredHolder<Item, Item> JOSIPDVATOCKANULA_SPAWN_EGG = REGISTRY.register("josipdvatockanula_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.JOSIPDVATOCKANULA, -16777216, -65536, new Item.Properties()));
	public static final DeferredHolder<Item, Item> TURTLE_ARMOR_CHESTPLATE = REGISTRY.register("turtle_armor_chestplate", () -> new TurtleArmorItem.Chestplate());
	public static final DeferredHolder<Item, Item> TURTLE_ARMOR_LEGGINGS = REGISTRY.register("turtle_armor_leggings", () -> new TurtleArmorItem.Leggings());
	public static final DeferredHolder<Item, Item> TURTLE_ARMOR_BOOTS = REGISTRY.register("turtle_armor_boots", () -> new TurtleArmorItem.Boots());
	public static final DeferredHolder<Item, Item> BEEF_ARMOR_HELMET = REGISTRY.register("beef_armor_helmet", () -> new BeefArmorItem.Helmet());
	public static final DeferredHolder<Item, Item> BEEF_ARMOR_CHESTPLATE = REGISTRY.register("beef_armor_chestplate", () -> new BeefArmorItem.Chestplate());
	public static final DeferredHolder<Item, Item> BEEF_ARMOR_LEGGINGS = REGISTRY.register("beef_armor_leggings", () -> new BeefArmorItem.Leggings());
	public static final DeferredHolder<Item, Item> BEEF_ARMOR_BOOTS = REGISTRY.register("beef_armor_boots", () -> new BeefArmorItem.Boots());
	public static final DeferredHolder<Item, Item> JOSIP_PET_SPAWN_EGG = REGISTRY.register("josip_pet_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.JOSIP_PET, -3407668, -26113, new Item.Properties()));
	public static final DeferredHolder<Item, Item> JOSIP_PETT_SPAWN_EGG = REGISTRY.register("josip_pett_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.JOSIP_PETT, -65536, -10066330, new Item.Properties()));
	public static final DeferredHolder<Item, Item> MOTH_OF_AGGREVATION_SPAWN_EGG = REGISTRY.register("moth_of_aggrevation_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.MOTH_OF_AGGREVATION, -6737152, -1, new Item.Properties()));
	public static final DeferredHolder<Item, Item> BULLET = REGISTRY.register("bullet", () -> new BulletItem());
	public static final DeferredHolder<Item, Item> SHEP_SPAWN_EGG = REGISTRY.register("shep_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.SHEP, -1, -10066330, new Item.Properties()));
	public static final DeferredHolder<Item, Item> VIKKIVUK_SPAWN_EGG = REGISTRY.register("vikkivuk_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.VIKKIVUK, -13369345, -13408513, new Item.Properties()));
	public static final DeferredHolder<Item, Item> BLAZ_SPAWN_EGG = REGISTRY.register("blaz_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.BLAZ, -205, -39322, new Item.Properties()));
	public static final DeferredHolder<Item, Item> CURSED_DOG_SPAWN_EGG = REGISTRY.register("cursed_dog_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.CURSED_DOG, -1, -3355444, new Item.Properties()));
	public static final DeferredHolder<Item, Item> METH = REGISTRY.register("meth", () -> new MethItem());
	public static final DeferredHolder<Item, Item> WALTER_WIGHT_SPAWN_EGG = REGISTRY.register("walter_wight_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.WALTER_WIGHT, -16777012, -16777114, new Item.Properties()));
	public static final DeferredHolder<Item, Item> ADOLF_HITLER_SPAWN_EGG = REGISTRY.register("adolf_hitler_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.ADOLF_HITLER, -52429, -3407872, new Item.Properties()));
	public static final DeferredHolder<Item, Item> DREAM_SPAWN_EGG = REGISTRY.register("dream_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.DREAM, -13369549, -1, new Item.Properties()));
	public static final DeferredHolder<Item, Item> SCRATEST = REGISTRY.register("scratest", () -> new ScratestItem());
	public static final DeferredHolder<Item, Item> YOUTUBE = block(PurechaosModBlocks.YOUTUBE);
	public static final DeferredHolder<Item, Item> PLANTE = block(PurechaosModBlocks.PLANTE);
	public static final DeferredHolder<Item, Item> TESTICLE_ON_STICK = REGISTRY.register("testicle_on_stick", () -> new TesticleOnStickItem());
	public static final DeferredHolder<Item, Item> RICKROLL_BLOCK = block(PurechaosModBlocks.RICKROLL_BLOCK);
	public static final DeferredHolder<Item, Item> GRAVE = block(PurechaosModBlocks.GRAVE);
	public static final DeferredHolder<Item, Item> MILK_2_BUCKET = REGISTRY.register("milk_2_bucket", () -> new Milk2Item());
	public static final DeferredHolder<Item, Item> USE_IN_EMERGENCIES = REGISTRY.register("use_in_emergencies", () -> new UseInEmergenciesItem());
	public static final DeferredHolder<Item, Item> COD_BUT_BETTER_SPAWN_EGG = REGISTRY.register("cod_but_better_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.COD_BUT_BETTER, -13312, -13108, new Item.Properties()));
	public static final DeferredHolder<Item, Item> BACKROOMS_LVL_1LIGHT = block(PurechaosModBlocks.BACKROOMS_LVL_1LIGHT);
	public static final DeferredHolder<Item, Item> SSSR = REGISTRY.register("sssr", () -> new SSSRItem());
	public static final DeferredHolder<Item, Item> STALIN_SPAWN_EGG = REGISTRY.register("stalin_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.STALIN, -65536, -11776, new Item.Properties()));
	public static final DeferredHolder<Item, Item> RICK_ASTLEY_SPAWN_EGG = REGISTRY.register("rick_astley_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.RICK_ASTLEY, -1, -1, new Item.Properties()));
	public static final DeferredHolder<Item, Item> BACKROOMS_LVL_1_WALL = block(PurechaosModBlocks.BACKROOMS_LVL_1_WALL);
	public static final DeferredHolder<Item, Item> RADIATION_LIQUID_BUCKET = REGISTRY.register("radiation_liquid_bucket", () -> new RadiationLiquidItem());
	public static final DeferredHolder<Item, Item> BLEACH = REGISTRY.register("bleach", () -> new BleachItem());
	public static final DeferredHolder<Item, Item> BRAZIL_BLOCK = block(PurechaosModBlocks.BRAZIL_BLOCK);
	public static final DeferredHolder<Item, Item> NOKIA_BLOCK = block(PurechaosModBlocks.NOKIA_BLOCK);
	public static final DeferredHolder<Item, Item> BRAZIL = REGISTRY.register("brazil", () -> new BrazilItem());
	public static final DeferredHolder<Item, Item> BACKROOMS_LVL_1_FLOOR = block(PurechaosModBlocks.BACKROOMS_LVL_1_FLOOR);
	public static final DeferredHolder<Item, Item> SOUTH = block(PurechaosModBlocks.SOUTH);
	public static final DeferredHolder<Item, Item> LEGS_SPAWN_EGG = REGISTRY.register("legs_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.LEGS, -26368, -205, new Item.Properties()));
	public static final DeferredHolder<Item, Item> LONG_LEG_CHICKEN_SPAWN_EGG = REGISTRY.register("long_leg_chicken_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.LONG_LEG_CHICKEN, -3355444, -16777216, new Item.Properties()));
	public static final DeferredHolder<Item, Item> FIREFLY_SPAWN_EGG = REGISTRY.register("firefly_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.FIREFLY, -16777216, -13261, new Item.Properties()));
	public static final DeferredHolder<Item, Item> TOTEM_OF_AMOGUS = REGISTRY.register("totem_of_amogus", () -> new TotemOfAmogusItem());
	public static final DeferredHolder<Item, Item> DEPRESSION_BLOCK = block(PurechaosModBlocks.DEPRESSION_BLOCK);
	public static final DeferredHolder<Item, Item> T_POSE_ENTITY_SPAWN_EGG = REGISTRY.register("t_pose_entity_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.T_POSE_ENTITY, -1, -16777216, new Item.Properties()));
	public static final DeferredHolder<Item, Item> IMPOSTOR_KNIFE = REGISTRY.register("impostor_knife", () -> new ImpostorKnifeItem());
	public static final DeferredHolder<Item, Item> SAMSUNG_NOTE_7 = REGISTRY.register("samsung_note_7", () -> new SamsungNote7Item());
	public static final DeferredHolder<Item, Item> ALMOND_WATER = REGISTRY.register("almond_water", () -> new AlmondWaterItem());
	public static final DeferredHolder<Item, Item> ZENITH = REGISTRY.register("zenith", () -> new ZenithItem());
	public static final DeferredHolder<Item, Item> COMUNISAM_BLOCK = block(PurechaosModBlocks.COMUNISAM_BLOCK);
	public static final DeferredHolder<Item, Item> POLAND_BLOCK = block(PurechaosModBlocks.POLAND_BLOCK);
	public static final DeferredHolder<Item, Item> CYBER_BLOCK = block(PurechaosModBlocks.CYBER_BLOCK);
	public static final DeferredHolder<Item, Item> TOTEM_OF_DREAM = REGISTRY.register("totem_of_dream", () -> new TotemOfDreamItem());
	public static final DeferredHolder<Item, Item> COMPUTER = block(PurechaosModBlocks.COMPUTER);
	public static final DeferredHolder<Item, Item> IGLA = REGISTRY.register("igla", () -> new IglaItem());
	public static final DeferredHolder<Item, Item> CIOAO = REGISTRY.register("cioao", () -> new CioaoItem());
	public static final DeferredHolder<Item, Item> TO = REGISTRY.register("to", () -> new TOItem());
	public static final DeferredHolder<Item, Item> FORTNITE_A_1 = REGISTRY.register("fortnite_a_1", () -> new FortniteA1Item());
	public static final DeferredHolder<Item, Item> GREENGISCREENDA = block(PurechaosModBlocks.GREENGISCREENDA);
	public static final DeferredHolder<Item, Item> FASTTOPASS = REGISTRY.register("fasttopass", () -> new FASTTOPASSItem());
	public static final DeferredHolder<Item, Item> STROATER_SPAWN_EGG = REGISTRY.register("stroater_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.STROATER, -6724096, -16777216, new Item.Properties()));
	public static final DeferredHolder<Item, Item> HALF_GOLDEN_APPLE = REGISTRY.register("half_golden_apple", () -> new HalfGoldenAppleItem());
	public static final DeferredHolder<Item, Item> BEEF = REGISTRY.register("beef", () -> new BeefItem());
	public static final DeferredHolder<Item, Item> BAGUETTE = REGISTRY.register("baguette", () -> new BaguetteItem());
	public static final DeferredHolder<Item, Item> OBAMIUM = REGISTRY.register("obamium", () -> new ObamiumItem());
	public static final DeferredHolder<Item, Item> LAVA_BOTTLE = REGISTRY.register("lava_bottle", () -> new LavaBottleItem());
	public static final DeferredHolder<Item, Item> SPONGEBOB_BOSS_SPAWN_EGG = REGISTRY.register("spongebob_boss_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.SPONGEBOB_BOSS, -256, -3355648, new Item.Properties()));
	public static final DeferredHolder<Item, Item> COBBLE_FLUID_BUCKET = REGISTRY.register("cobble_fluid_bucket", () -> new CobbleFluidItem());
	public static final DeferredHolder<Item, Item> BEENGOT = REGISTRY.register("beengot", () -> new BeengotItem());
	public static final DeferredHolder<Item, Item> ADIDAS_ARMOR_HELMET = REGISTRY.register("adidas_armor_helmet", () -> new AdidasArmorItem.Helmet());
	public static final DeferredHolder<Item, Item> ADIDAS_ARMOR_CHESTPLATE = REGISTRY.register("adidas_armor_chestplate", () -> new AdidasArmorItem.Chestplate());
	public static final DeferredHolder<Item, Item> ADIDAS_ARMOR_LEGGINGS = REGISTRY.register("adidas_armor_leggings", () -> new AdidasArmorItem.Leggings());
	public static final DeferredHolder<Item, Item> ADIDAS_ARMOR_BOOTS = REGISTRY.register("adidas_armor_boots", () -> new AdidasArmorItem.Boots());
	public static final DeferredHolder<Item, Item> ADIDAS_SWORD = REGISTRY.register("adidas_sword", () -> new AdidasSwordItem());
	public static final DeferredHolder<Item, Item> ADIDAS_SHOVEL = REGISTRY.register("adidas_shovel", () -> new AdidasShovelItem());
	public static final DeferredHolder<Item, Item> ADIDAS_BLOCK = block(PurechaosModBlocks.ADIDAS_BLOCK);
	public static final DeferredHolder<Item, Item> ADIDAS_AXE = REGISTRY.register("adidas_axe", () -> new AdidasAxeItem());
	public static final DeferredHolder<Item, Item> AMOGUS_3_BLU_SPAWN_EGG = REGISTRY.register("amogus_3_blu_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.AMOGUS_3_BLU, -52429, -13382401, new Item.Properties()));
	public static final DeferredHolder<Item, Item> ADIDAS_HOE = REGISTRY.register("adidas_hoe", () -> new AdidasHoeItem());
	public static final DeferredHolder<Item, Item> ADIDAS_PICKAXE = REGISTRY.register("adidas_pickaxe", () -> new AdidasPickaxeItem());
	public static final DeferredHolder<Item, Item> AMOGUS_3_GRIN_SPAWN_EGG = REGISTRY.register("amogus_3_grin_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.AMOGUS_3_GRIN, -52429, -10027162, new Item.Properties()));
	public static final DeferredHolder<Item, Item> MISSING_TEXTURE = block(PurechaosModBlocks.MISSING_TEXTURE);
	public static final DeferredHolder<Item, Item> THE_ROCK_SPAWN_EGG = REGISTRY.register("the_rock_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.THE_ROCK, -3394816, -52480, new Item.Properties()));
	public static final DeferredHolder<Item, Item> EATABLE_COMMAND_BLOCK = REGISTRY.register("eatable_command_block", () -> new EatableCommandBlockItem());
	public static final DeferredHolder<Item, Item> XSORD = REGISTRY.register("xsord", () -> new XSORDItem());
	public static final DeferredHolder<Item, Item> XITE = REGISTRY.register("xite", () -> new XiteItem());
	public static final DeferredHolder<Item, Item> BOTTLE_OF_PISS = REGISTRY.register("bottle_of_piss", () -> new BottleOfPissItem());
	public static final DeferredHolder<Item, Item> TINTED_GLASS_BOTTLE = REGISTRY.register("tinted_glass_bottle", () -> new TintedGlassBottleItem());
	public static final DeferredHolder<Item, Item> IRON_EGG = REGISTRY.register("iron_egg", () -> new IronEggItem());
	public static final DeferredHolder<Item, Item> DORITO_COOL_RANCH = REGISTRY.register("dorito_cool_ranch", () -> new DoritoCoolRanchItem());
	public static final DeferredHolder<Item, Item> DORITO_NACHO = REGISTRY.register("dorito_nacho", () -> new DoritoNachoItem());
	public static final DeferredHolder<Item, Item> KENTUCKY_FRIED_CHICKEN_FRIES = REGISTRY.register("kentucky_fried_chicken_fries", () -> new KentuckyFriedChickenFriesItem());
	public static final DeferredHolder<Item, Item> KENTUCKY_FRIED_CHICKEN = REGISTRY.register("kentucky_fried_chicken", () -> new KentuckyFriedChickenItem());
	public static final DeferredHolder<Item, Item> KFCE = REGISTRY.register("kfce", () -> new KFCEItem());
	public static final DeferredHolder<Item, Item> BIG_SPAWN_EGG = REGISTRY.register("big_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.BIG, -16777216, -3355648, new Item.Properties()));
	public static final DeferredHolder<Item, Item> AETHER = REGISTRY.register("aether", () -> new AetherItem());
	public static final DeferredHolder<Item, Item> SPIT_BALL = REGISTRY.register("spit_ball", () -> new SpitBallItem());
	public static final DeferredHolder<Item, Item> GLOW = REGISTRY.register("glow", () -> new GlowItem());
	public static final DeferredHolder<Item, Item> MERCURY = REGISTRY.register("mercury", () -> new MercuryItem());
	public static final DeferredHolder<Item, Item> JEB_BLOCK = block(PurechaosModBlocks.JEB_BLOCK);
	public static final DeferredHolder<Item, Item> FRYING_PAN = REGISTRY.register("frying_pan", () -> new FryingPanItem());
	public static final DeferredHolder<Item, Item> APPLE_INGOT = REGISTRY.register("apple_ingot", () -> new AppleIngotItem());
	public static final DeferredHolder<Item, Item> TECHNOBLADE_SPAWN_EGG = REGISTRY.register("technoblade_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.TECHNOBLADE, -39271, -3342541, new Item.Properties()));
	public static final DeferredHolder<Item, Item> CUPCAKKE_SPAWN_EGG = REGISTRY.register("cupcakke_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.CUPCAKKE, -1, -1, new Item.Properties()));
	public static final DeferredHolder<Item, Item> DINGOT = REGISTRY.register("dingot", () -> new DingotItem());
	public static final DeferredHolder<Item, Item> POOP = REGISTRY.register("poop", () -> new PoopItem());
	public static final DeferredHolder<Item, Item> BALDI_MINUS_SPAWN_EGG = REGISTRY.register("baldi_minus_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.BALDI_MINUS, -11618049, -16711936, new Item.Properties()));
	public static final DeferredHolder<Item, Item> HEROBRINE_SPAWN_EGG = REGISTRY.register("herobrine_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.HEROBRINE, -1, -9777153, new Item.Properties()));
	public static final DeferredHolder<Item, Item> COMMUNISM_ORB = REGISTRY.register("communism_orb", () -> new CommunismOrbItem());
	public static final DeferredHolder<Item, Item> COCA_COLA = REGISTRY.register("coca_cola", () -> new CocaColaItem());
	public static final DeferredHolder<Item, Item> NERD_SPAWN_EGG = REGISTRY.register("nerd_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.NERD, -205, -3355444, new Item.Properties()));
	public static final DeferredHolder<Item, Item> SUSSY_SUS_STEW = REGISTRY.register("sussy_sus_stew", () -> new SussySusStewItem());
	public static final DeferredHolder<Item, Item> IRS_SPAWN_EGG = REGISTRY.register("irs_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.IRS, -13312, -16776961, new Item.Properties()));
	public static final DeferredHolder<Item, Item> FBI_SPAWN_EGG = REGISTRY.register("fbi_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.FBI, -10066330, -16777216, new Item.Properties()));
	public static final DeferredHolder<Item, Item> AMERICAN_SOLDAT_SPAWN_EGG = REGISTRY.register("american_soldat_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.AMERICAN_SOLDAT, -6684826, -10066330, new Item.Properties()));
	public static final DeferredHolder<Item, Item> MURICA_SPAWN_EGG = REGISTRY.register("murica_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.MURICA, -13421569, -65536, new Item.Properties()));
	public static final DeferredHolder<Item, Item> GRIMACE_SHAKE = REGISTRY.register("grimace_shake", () -> new GrimaceShakeItem());
	public static final DeferredHolder<Item, Item> DEEK = REGISTRY.register("deek", () -> new DeekItem());
	public static final DeferredHolder<Item, Item> KONDOMNEPITAJZASTOOVORADIMALISPOILERALERTONIMARUPU = REGISTRY.register("kondomnepitajzastoovoradimalispoileralertonimarupu", () -> new KondomnepitajzastoovoradimalispoileralertonimarupuItem());
	public static final DeferredHolder<Item, Item> WATER_CUP = REGISTRY.register("water_cup", () -> new WaterCupItem());
	public static final DeferredHolder<Item, Item> JOSIP_RANGE = REGISTRY.register("josip_range", () -> new JosipRangeItem());
	public static final DeferredHolder<Item, Item> AK_47 = REGISTRY.register("ak_47", () -> new AK47Item());
	public static final DeferredHolder<Item, Item> AMOGUS_GUN = REGISTRY.register("amogus_gun", () -> new AmogusGunItem());
	public static final DeferredHolder<Item, Item> ROCK = REGISTRY.register("rock", () -> new RockItem());
	public static final DeferredHolder<Item, Item> JAVELIN_LAUNCHER = REGISTRY.register("javelin_launcher", () -> new JavelinLauncherItem());
	public static final DeferredHolder<Item, Item> PENSIVE_CUBE_SPAWN_EGG = REGISTRY.register("pensive_cube_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.PENSIVE_CUBE, -10066330, -256, new Item.Properties()));
	public static final DeferredHolder<Item, Item> PUFFER_BALLOON = REGISTRY.register("puffer_balloon", () -> new PufferBalloonItem());
	public static final DeferredHolder<Item, Item> INFINITE_FUEL = REGISTRY.register("infinite_fuel", () -> new InfiniteFuelItem());
	public static final DeferredHolder<Item, Item> GROGGO_SPAWN_EGG = REGISTRY.register("groggo_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.GROGGO, -16724992, -6737152, new Item.Properties()));
	public static final DeferredHolder<Item, Item> BRAKE_FLUID = REGISTRY.register("brake_fluid", () -> new BrakeFluidItem());
	public static final DeferredHolder<Item, Item> BACKROOM_WALL_BOTTOM = block(PurechaosModBlocks.BACKROOM_WALL_BOTTOM);
	public static final DeferredHolder<Item, Item> BACKROOMS_CEILING = block(PurechaosModBlocks.BACKROOMS_CEILING);
	public static final DeferredHolder<Item, Item> MELATONIN_PILL = REGISTRY.register("melatonin_pill", () -> new MelatoninPillItem());
	public static final DeferredHolder<Item, Item> RAINBOWRACK = block(PurechaosModBlocks.RAINBOWRACK);
	public static final DeferredHolder<Item, Item> RAINBOW_GRASS = block(PurechaosModBlocks.RAINBOW_GRASS);
	public static final DeferredHolder<Item, Item> POLAND_ITEM = REGISTRY.register("poland_item", () -> new PolandItemItem());
	public static final DeferredHolder<Item, Item> YUGOSLAVIA_SPAWN_EGG = REGISTRY.register("yugoslavia_spawn_egg", () -> new DeferredSpawnEggItem(PurechaosModEntities.YUGOSLAVIA, -65485, -16776961, new Item.Properties()));
	public static final DeferredHolder<Item, Item> FISH_LAUNCHER = REGISTRY.register("fish_launcher", () -> new FishLauncherItem());
	public static final DeferredHolder<Item, Item> EDIBLE_WATER_BUCKET = REGISTRY.register("edible_water_bucket", () -> new EdibleWaterBucketItem());

	// Start of user code block custom items
	// End of user code block custom items
	public static void register(IEventBus bus) {
		REGISTRY.register(bus);
	}

	private static DeferredHolder<Item, Item> block(DeferredHolder<Block, Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
