modLoader="javafml"
loaderVersion="[4,)"
license="All rights reserved"

[[mods]]
modId="purechaos"
version="2025.2"
displayName="Pure Chaos"
displayURL="https://modrinth.com/mod/chaos"
logoFile="logo.png"
credits="too many stolen ideas and coffee"
authors="Aflkonstukt Studio"
description="umm... guys..?"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.purechaos]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.92,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.purechaos]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.purechaos]]
    modId="jei"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration